---
- name: Install virtualization packages
  package:
    name: 
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvm
      - virt-install
      - edk2-ovmf
    state: present

- name: Install systemd-networkd
  package:
    name: systemd-networkd
    state: present
  register: layersAdded

- name: Copy over bridge interface config
  copy: 
    src: files/br.netdev
    dest: /etc/systemd/network/br.netdev

- name: Copy over binding interface config
  copy: 
    src: files/1-br0-bind.network
    dest: /etc/systemd/network/1-br0-bind.network

- name: Copy over dhcp interface config
  copy: 
    src: files/2-br0-dhcp.network
    dest: /etc/systemd/network/2-br0-dhcp.network

- name: Stop and disable NetworkManager
  systemd:
    name: NetworkManager
    enabled: false

- name: Start and enable systemd-networkd
  systemd:
    name: systemd-networkd
    enabled: true
