---
- name: Install virtualization packages
  community.general.rpm_ostree_pkg:
    name: 
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvm
      - virt-install
    state: present
  notify:
  - Reboot if required

- name: Install systemd-networkd
  community.general.rpm_ostree_pkg:
    name: systemd-networkd
    state: present
  register: layersAdded

- name: Reboot if required
  reboot:
  when: layersAdded.changed

- name: Copy over bridge interface configuration
  copy: 
    src: files/br.netdev
    dest: /etc/systemd/network/br.netdev

- name: Copy over interface bind configuration
  copy: 
    src: files/1-br0-bind.network
    dest: /etc/systemd/network/1-br0-bind.network

- name: Copy over bridge interface configuration
  copy: 
    src: files/2-br0-dhcp.network
    dest: /etc/systemd/network/2-br0-dhcp.network

- name: Stop and disable NetworkManager
  systemd:
    name: NetworkManager
    state: stopped
    enabled: false

- name: Start and enable systemd-networkd
  systemd:
    name: systemd-networkd
    state: started
    enabled: true
